name: Build C++ DLL and Java Maven project

on: push

env:
  JAVA_VERSION: '8'

jobs:
  build:
    runs-on: windows-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup Java Sdk ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}
  
    - name: 'Create "dependencies" directory'
      shell: pwsh
      run: |
        [IO.Directory]::CreateDirectory("dependencies")
  
    - name: 'The ADS API is available as a secret. It is a base64-encoded .zip file.'
      shell: pwsh
      env:
        ADS_API_ZIP_BASE64: ${{ secrets.ADS_API_ZIP_BASE64 }}
      run: |
        [IO.File]::WriteAllBytes("dependencies\AdsApi.zip", [Convert]::FromBase64String("$env:ADS_API_ZIP_BASE64"))
  
    - name: 'Put the contents of the "AdsApi.zip" archive into the "dependencies" directory.'
      shell: pwsh
      run: |
        Expand-Archive "dependencies\AdsApi.zip" -DestinationPath dependencies\

    - name: 'Run the bootstrap batch script'
      shell: cmd
      run: |
        CALL bootstrap.bat
